---
  name: javascript-ci

  on:
    pull_request:
      branches:
      - main
      paths-ignore:
      - '**.md'
      - '.github/workflows/codeql.yml'
      - './docs/**'

  jobs:
    validation:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [16.x, 18.x]
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: Install Dependencies
          run: npm install
        - name: npm test
          run: npm test
        - name: npm build
          run: npm run build
        - name: Verify dist is up to date
          run: |
            if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
              echo "Detected uncommitted changes after npm build.  See status below:" >> $GITHUB_STEP_SUMMARY
              echo "\`\`\`plain" >> $GITHUB_STEP_SUMMARY
              echo "$(git diff)" >> $GITHUB_STEP_SUMMARY
              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
              echo "dist/index.js is not up to date.  Please execute 'npm run build' and commit the changes." >> $GITHUB_STEP_SUMMARY
              exit 1
            fi
          id: diff
    integration:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 18.x
          uses: actions/setup-node@v3
          with:
            node-version: 18.x
            cache: 'npm'
        - name: Install Dependencies
          run: npm install
        - name: start server
          run: nohup npm start &
        - name: wait for server to start
          run: until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do printf '.'; sleep 5; done
        - name: run integration tests
          run: npm run test::integration
