# This is an aggregate workflow which calls other workflows, as required.
# Calling other jobs in this way allows for easier visualization of the workflows and their dependencies.
name: PR-Validation

on:
  pull_request:

jobs:
  dependency-review:
    uses: ./.github/workflows/dependency-review.yml
    permissions:
      contents: read
  ci-javascript:
    uses: ./.github/workflows/ci-js.yml
    needs:
      - dependency-review
  CodeQL:
    uses: ./.github/workflows/codeql.yml
    needs:
      - dependency-review
    permissions:
      actions: read
      contents: read
      security-events: write
  build-docker:
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write
    needs:
      - ci-javascript
      - CodeQL
