# This is an aggregate workflow which calls other workflows, as required.
# Calling other jobs in this way allows for easier visualization of the workflows and their dependencies.
name: PR-Validation

on:
  pull_request:

jobs:
  ci-javascript:
    uses: ./.github/workflows/ci-js.yml
  CodeQL:
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
  build-docker:
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write
    needs:
      - ci-javascript
      - CodeQL
      - dependency-review
